void sounds () {
  if (cm <= 5) {
      tone(8, 2000);
      digitalWrite(redLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(redLed, LOW);
            delay(100);
      tone(8, 2000);
      digitalWrite(redLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(redLed, LOW);
            delay(100);
      tone(8, 2000);
      digitalWrite(redLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(redLed, LOW);
            delay(100);
      tone(8, 2000);
      digitalWrite(redLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(redLed, LOW);
                  delay(100);
      tone(8, 2000);
      digitalWrite(redLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(redLed, LOW);
                        delay(100);
      tone(8, 2000);
      digitalWrite(redLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(redLed, LOW);
                        delay(100);
      tone(8, 2000);
      digitalWrite(redLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(redLed, LOW);
                        delay(100);
      tone(8, 2000);
      digitalWrite(redLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(redLed, LOW);
                        delay(100);
      tone(8, 2000);
      digitalWrite(redLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(redLed, LOW);
                        delay(100);
      tone(8, 2000);
      digitalWrite(redLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(redLed, LOW);
                        delay(100);
      tone(8, 2000);
      digitalWrite(redLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(redLed, LOW);
                        delay(100);
      tone(8, 2000);
      digitalWrite(redLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(redLed, LOW);
                        delay(100);
      tone(8, 2000);
      delay(100);
      noTone(8);
                        delay(100);
      tone(8, 2000);
      digitalWrite(redLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(redLed, LOW);
                        delay(100);
      tone(8, 2000);
      digitalWrite(redLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(redLed, LOW);
                        delay(100);
      tone(8, 2000);
      digitalWrite(redLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(redLed, LOW);
                        delay(100);
      tone(8, 2000);
      digitalWrite(redLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(redLed, LOW);
                        delay(100);
      tone(8, 2000);
      digitalWrite(redLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(redLed, LOW);
      
  }
  else if(cm <= 15) {
      tone(8, 1500);
      digitalWrite(redLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(redLed, LOW);
                              delay(100);
      tone(8, 1500);
      digitalWrite(redLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(redLed, LOW);
                              delay(100);
      tone(8, 1500);
      digitalWrite(redLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(redLed, LOW);
                              delay(100);
      tone(8, 1500);
      digitalWrite(redLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(redLed, LOW);
                              delay(100);
       tone(8, 1500);
      digitalWrite(redLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(redLed, LOW);
                              delay(100);
      tone(8, 1500);
      digitalWrite(redLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(redLed, LOW);
                              delay(100);
      tone(8, 1500);
      digitalWrite(redLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(redLed, LOW);
                              delay(100);
      tone(8, 1500);
      digitalWrite(redLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(redLed, LOW);
                              delay(100);
      tone(8, 1500);
      digitalWrite(redLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(redLed, LOW);
                              delay(100);
       tone(8, 1500);
      digitalWrite(redLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(redLed, LOW);
                              delay(100);
      tone(8, 1500);
      digitalWrite(redLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(redLed, LOW);
                              delay(100);
      tone(8, 1500);
      digitalWrite(redLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(redLed, LOW);
                              delay(100);
      tone(8, 1500);
      digitalWrite(redLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(redLed, LOW);
                              delay(100);
      tone(8, 1500);
      digitalWrite(redLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(redLed, LOW);
                              delay(100);
      tone(8, 1500);
      digitalWrite(redLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(redLed, LOW);
                              delay(100);
      tone(8, 1500);
      digitalWrite(redLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(redLed, LOW);
                              delay(100);
      tone(8, 1500);
      digitalWrite(redLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(redLed, LOW);
                              delay(100);
      tone(8, 1500);
      digitalWrite(redLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(redLed, LOW);
      
  }
    else if(cm <= 30) {
      tone(8, 1200);
            digitalWrite(yellowLed, HIGH);
      delay(100);
      noTone(8);
      digitalWrite(yellowLed, LOW);
            delay(100);
                  tone(8, 1200);
                  digitalWrite(yellowLed, HIGH);
      delay(100);
      noTone(8);
            digitalWrite(yellowLed, LOW);
            delay(100);
                  tone(8, 1200);
                  digitalWrite(yellowLed, HIGH);
      delay(100);
      noTone(8);
            digitalWrite(yellowLed, LOW);
            delay(100);
                  tone(8, 1200);
                  digitalWrite(yellowLed, HIGH);
      delay(100);
      noTone(8);
            digitalWrite(yellowLed, LOW);
            delay(100);
                  tone(8, 1200);
                  digitalWrite(yellowLed, HIGH);
      delay(100);
      noTone(8);
            digitalWrite(yellowLed, LOW);
            delay(100);
                  tone(8, 1200);
                  digitalWrite(yellowLed, HIGH);
      delay(100);
      noTone(8);
            digitalWrite(yellowLed, LOW);
            delay(100);
                  tone(8, 1200);
                  digitalWrite(yellowLed, HIGH);
      delay(100);
      noTone(8);
            digitalWrite(yellowLed, LOW);
            delay(100);
                  tone(8, 1200);
                  digitalWrite(yellowLed, HIGH);
      delay(100);
      noTone(8);
            digitalWrite(yellowLed, LOW);
            delay(100);
                  tone(8, 1200);
                  digitalWrite(yellowLed, HIGH);
      delay(100);
      noTone(8);
            digitalWrite(yellowLed, LOW);
            delay(100);
                  tone(8, 1200);
                  digitalWrite(yellowLed, HIGH);
      delay(100);
      noTone(8);
            digitalWrite(yellowLed, LOW);
            delay(100);
                  tone(8, 1200);
                  digitalWrite(yellowLed, HIGH);
      delay(100);
      noTone(8);
            digitalWrite(yellowLed, LOW);
            delay(100);      
            tone(8, 1200);
            digitalWrite(yellowLed, HIGH);
      delay(100);
      noTone(8);
            digitalWrite(yellowLed, LOW);
            delay(100);
                  tone(8, 1200);
                  digitalWrite(yellowLed, HIGH);
      delay(100);
      noTone(8);      
      digitalWrite(yellowLed, LOW);
            delay(100);
                  tone(8, 1200);
                  digitalWrite(yellowLed, HIGH);
      delay(100);
      noTone(8);
            digitalWrite(yellowLed, LOW);
            delay(100);
                  tone(8, 1200);
                  digitalWrite(yellowLed, HIGH);
      delay(100);
      
      noTone(8);
            digitalWrite(yellowLed, LOW);
            delay(100);
                  tone(8, 1200);
                  digitalWrite(yellowLed, HIGH);
      delay(100);
      noTone(8);
            digitalWrite(yellowLed, LOW);
            delay(100);
                  tone(8, 1200);
                  digitalWrite(yellowLed, HIGH);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 1200);
                  digitalWrite(yellowLed, HIGH);
      delay(100);
      noTone(8);
            digitalWrite(yellowLed, LOW);
            delay(100);
                  tone(8, 1200);
                  digitalWrite(yellowLed, HIGH);
      delay(100);
      noTone(8);
            digitalWrite(yellowLed, LOW);
            delay(100);
                  tone(8, 1200);
                  digitalWrite(yellowLed, HIGH);
      delay(100);
      noTone(8);
            digitalWrite(yellowLed, LOW);
            delay(100);
                  tone(8, 1200);
                  digitalWrite(yellowLed, HIGH);
      delay(100);
      noTone(8);
            digitalWrite(yellowLed, LOW);
            delay(100);
                  tone(8, 1200);
                  digitalWrite(yellowLed, HIGH);
      delay(100);
      noTone(8);
            digitalWrite(yellowLed, LOW);
            delay(100);
                  tone(8, 1200);
                  digitalWrite(yellowLed, HIGH);
      delay(100);
      noTone(8);
            digitalWrite(yellowLed, LOW);
            delay(100);
                  tone(8, 1200);
                  digitalWrite(yellowLed, HIGH);
      delay(100);
      noTone(8);
            digitalWrite(yellowLed, LOW);
            delay(100);
                  tone(8, 1200);
                  digitalWrite(yellowLed, HIGH);
      delay(100);
      noTone(8);
            digitalWrite(yellowLed, LOW);
            delay(100);
                  tone(8, 1200);
                  digitalWrite(yellowLed, HIGH);
      delay(100);
      noTone(8);
            digitalWrite(yellowLed, LOW);
            delay(100);
      
  }
    else if(cm <= 60) {
      tone(8, 600);
      delay(100);
      noTone(8);
      delay(100);
            tone(8, 600);
      delay(100);
      noTone(8);
      delay(100);
            tone(8, 600);
      delay(100);
      noTone(8);
      delay(100);
            tone(8, 600);
      delay(100);
      noTone(8);
      delay(100);
            tone(8, 600);
      delay(100);
      noTone(8);
      delay(100);
            tone(8, 600);
      delay(100);
      noTone(8);
      delay(100);
            tone(8, 600);
      delay(100);
      noTone(8);
      delay(100);
            tone(8, 600);
      delay(100);
      noTone(8);
      delay(100);
            tone(8, 600);
      delay(100);
      noTone(8);
      delay(100);
            tone(8, 600);
      delay(100);
      noTone(8);
      delay(100);
            tone(8, 600);
      delay(100);
      noTone(8);
      delay(100);      tone(8, 600);
      delay(100);
      noTone(8);
      delay(100);
            tone(8, 600);
      delay(100);
      noTone(8);
      delay(100);
            tone(8, 600);
      delay(100);
      noTone(8);
      delay(100);
            tone(8, 600);
      delay(100);
      noTone(8);
      delay(100);
            tone(8, 600);
      delay(100);
      noTone(8);
      delay(100);
            tone(8, 600);
      delay(100);
      noTone(8);
      delay(100);
            tone(8, 600);
      delay(100);
      noTone(8);
      delay(100);
            tone(8, 600);
      delay(100);
      noTone(8);
      
      
  }
      else if(cm <= 120) {
      tone(8, 300);
      delay(100);
      noTone(8);
            tone(8, 300);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 300);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 300);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 300);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 300);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 300);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 300);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 300);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 300);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 300);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 300);
      delay(100);
      noTone(8);
            delay(100);      tone(8, 300);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 300);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 300);
      delay(100);
      noTone(8);
 
      
  }
        else if(cm >= 120) {
      tone(8, 200);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 200);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 200);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 200);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 200);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 200);
      delay(100);
      noTone(8);
            delay(100);      tone(8, 200);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 200);
      delay(100);
      noTone(8);
            delay(100);      tone(8, 200);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 200);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 200);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 200);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 200);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 200);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 200);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 200);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 200);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 200);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 200);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 200);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 200);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 200);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 200);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 200);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 200);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 200);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 200);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 200);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 200);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 200);
      delay(100);
      noTone(8);
            delay(100);
                  tone(8, 200);
      delay(100);
      noTone(8);
      
  }
  delay(500);
  lcd.clear();
  delay(500);
  noTone(8);
}
